#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
# app_logout:
#     path: /logout
#     methods: GET

api_auth_login:
  path: /api/auth/login
  methods:  [POST]

api:
  prefix: /api
  resource: '../src/Controller/Api'